#ifndef PACKET_H
#define PACKET_H
#include <QString>
//消息类型枚举
enum MsgType
{
    LOGIN_REQUEST,
    LOGIN_REPLY,
    REGEIST_REQUEST,
    REGEIST_REPLY,
    LOADBOOK_REQUEST,
    LOADBOOK_REPLY,
    LOADBORROWINFO_REQUEST,
    LOADBORROWINFO_REPLY,
    FINDBOOK_REQUEST,
    FINDBOOK_REPLY,
    ADDBOOK_REQUEST,
    ADDBOOK_REPLY,
    DELETEBOOKS_REQUEST,
    DELETEBOOKS_REPLY,
    MODEFYBOOKS_REQUEST,
    MODEFYBOOKS_REPLY,
    BORROWBOOK_REQUEST,
    BORROWBOOK_REPLY,
    RETURNBOOK_REQUEST,
    RETURNBOOK_REPLY,
    SEARCHBORROWRECORD_REQUEST,
    SEARCHBORROWRECORD_REPLY,
    MODEFYPERSONALINFO_REQUEST,
    MODEFYPERSONALINFO_REPLY,
    MODEFYPASSWORD_REQUEST,
    MODEFYPASSWORD_REPLY,
    GETBOOKCOUNT_REQUEST,
    GETBOOKCOUNT_REPLY,
    FINDMYBORROWINFO_REQUEST,
    FINDMYBORROWINFO_REPLY,
    FINDBORROWCOUNTBYDATE_REQUEST,
    FINDBORROWCOUNTBYDATE_REPLY,
    GETREADERBORROWCOUNT_REQUEST,
    GETREADERBORROWCOUNT_REPLY
};
//消息处理状态枚举
enum Msg_Status
{
    SUCCESS,
    ERROR,
    ACCOUNT_OR_PASS_ERROR,
    ACCOUNT_REPEAT_ERROR,
    BOOKNOREPEATE_ERROR,
    BOOKNO_NOT_EXIT_ERROR,
    READERNO_NOT_EXIT_ERROR,
    OLDPASSWORD_ERROR,
    BORROWREPEATE_ERROR
};
const QString salt="thpl2077";//盐值，用于密码加密
#endif // PACKET_H
